name: Triggers
run-name: Estoy aprendiendo a usar diferentes Triggers
on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - "**.js"
    issues:
        types:
            - labeled
    workflow_dispatch:
        inputs:
            lenguaje_favorito:
                description: "Lenguaje favorito"
                default: JavaScript
                required: true
                type: choice
                options:
                    - JavaScript
                    - Python
                    - Go
            nombre:
                description: "Fidel Aguilar"
                required: true
                default: Fidel
                type: string
    schedule:
        - cron: "15 22 * * *"
jobs:
    hola-mundo-manual:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Definir nombre
              run: echo "USERNAME=${{ inputs.nombre }}" >> $GITHUB_ENV
            - name: Definir lenguaje favorito
              run: echo "LENGUAJE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV
            - name: Correr script
              run: node holaMundo.js
    hola-mundo:
        if: ${{ github.event_name != 'workflow_dispatch' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Definir variable
              run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
            - name: Correr script
              run: node holaMundo.js
